[package]
name = "yoot"
version = "0.1.0"
edition = "2021"

[dependencies]
binaryen = "0.12.1"
chumsky = "0.9.2"
clap = { version = "4.2.4", features = ["derive"] }
wasmtime = "29.0.1"
wasm-encoder = "*"
wasmprinter = "0.225.0"
